src/main/java/com/pondicherry/zoo/domain/Animal.java
package com.pondicherry.zoo.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import static javax.persistence.GenerationType.IDENTITY;
import java.io.Serializable;

@Entity
public class Animal implements Serializable {

    private Long id;
    private String name;
    private String iconFilename;

    // Default Constructor
    public Animal(){

    }

    @Id @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", unique = false, nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "icon_filename", unique = false, nullable = false)
    public String getFilename() {
        return iconFilename;
    }

    public void setFilename(String iconFilename) {
        this.iconFilename = iconFilename;
    }


}

src/main/java/com/pondicherry/zoo/web/controller/LoginController.java
package com.pondicherry.zoo.web.controller;

import com.pondicherry.zoo.domain.User;
import com.pondicherry.zoo.service.UserService;
import com.pondicherry.zoo.web.validators.LoginFormValidator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindException;
import org.springframework.validation.BindingResult;
import org.springframework.validation.Errors;
import org.springframework.validation.Validator;
import org.springframework.web.bind.ServletRequestDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.Map;


@Controller
@RequestMapping("/login.*")
public class LoginController extends SimpleFormController {

   private UserService userService;
  
   @Autowired
   public LoginController(UserService userService) {
   	this.userService = userService;
   }
   
   @RequestMapping(method = RequestMethod.GET)
   public String formBackingObject(Map<String, User> model) throws Exception {
       model.put("userCommand",new User());
       return "login";
   }

   @RequestMapping(method = RequestMethod.POST)
   public String submit(HttpServletRequest request, @ModelAttribute("userCommand") User command, BindingResult result) throws Exception {

   	new LoginFormValidator(userService).validate(command, result);
   	if (result.hasErrors()) {
   		return "login";
   	}
   	
       User user = userService.getUser(command.getUsername(), command.getPassword());

       // put the user into the session to indicate logged in status
       request.getSession().setAttribute("user", user);

       return "redirect:/home.html";
   }
 

   @InitBinder
   protected void initBinder(HttpServletRequest request, ServletRequestDataBinder binder) throws Exception {
   		 String[] allowedFields = {"username", "password"};
   		 binder.setAllowedFields(allowedFields);
   		}


}

src/main/webapp/WEB-INF/jsp/gallery.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<h1>Gallery</h1>

<p>
    Click <img src="images/coldStar.png" alt="Add to favourites"/> to add a favourite and
    <img src="images/hotStar.png" alt="Remove from favourites"/> to remove a favourite, or
    <a href="home.html">view just your favourites</a>.
</p>
<c:forEach items="${requestScope.allAnimals}" var="animal">
    <p>
        <span><img src="gallery/${animal.filename}" alt="${animal.filename}"></span>
        <c:choose>
            <c:when test="${requestScope.favourites[animal.id]}">
                <a href="removeFavourite.html?animalId=${animal.id}&gallery=true">
                    <img src="images/hotStar.png" alt="Remove from favourites"/>
                </a>
            </c:when>
            <c:otherwise>
                <a href="addFavourite.html?animalId=${animal.id}">
                    <img src="images/coldStar.png" alt="Add to favourites"/>
                </a>
            </c:otherwise>
        </c:choose>
    </p>
</c:forEach>

src/main/webapp/WEB-INF/jsp/header.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div>
    <c:if test="${not empty sessionScope.user}">
    You are logged in as ${sessionScope.user.username} (Sex: ${sessionScope.user.sex})
    (<a href="logout.html">Logout</a>)
</c:if>
</div>

src/main/webapp/WEB-INF/jsp/home.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<h1>My Favourites</h1>

<c:if test="${not empty requestScope.favourites}">
    <p>
        <a href="gallery.html">Browse the gallery</a> to find more favourites,
        or click <img src="images/hotStar.png" alt="Remove from favourites"/> below to remove
        a favourite.
    </p>
    <c:forEach items="${requestScope.favourites}" var="animal">
        <p>
            <img src="gallery/${animal.filename}" alt="${animal.name}">
            <a href="javascript:void(0);" onclick="removeFavourite('${animal.id}')">
                <img src="images/hotStar.png" alt="Remove from favourites"/>
            </a>
        </p>
    </c:forEach>
</c:if>

<c:if test="${empty requestScope.favourites}">
    <p>
        You don't have any favourites.
        <a href="gallery.html">Browse the gallery</a> to find some you like.
    </p>
</c:if>

src/main/webapp/WEB-INF/jsp/layout.jsp
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>

<html>
<head>
    <title>Whiteley's Zoo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <script type="text/javascript">
        function removeFavourite(animalId) {
            var proceed = confirm("Do you really want to remove this image from your favourites?");
            if (proceed) {
                window.location = "removeFavourite.html?animalId=" + animalId;
            }
        }
    </script>
</head>
<body>
<div id="headerWrap">
    <tiles:insertAttribute name="header"/>
</div>
<div id="navWrap">
    <tiles:insertAttribute name="nav"/>
</div>
<div id="bodyWrap">
    <tiles:insertAttribute name="body"/>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<div id="userForm">
    <form:form action="login.html" commandName="userCommand" method="POST">
        <table>
            <tbody>
            <tr>
                <th width="50%"/>
                <td><form:errors path="*" cssClass="redBold"/></td>
            </tr>
            <tr>
                <th><form:label path="username" cssErrorClass="redBold">Username</form:label></th>
                <td><form:input path="username"/></td>
            </tr>
            <tr>
                <th><form:label path="password" cssErrorClass="redBold">Password</form:label></th>
                <td><form:password path="password"/></td>
            </tr>
            <tr>
                <td/>
                <td><input type="submit" value="Login" class="button"/></td>
            </tr>
            <tr>
                <td/>
                <td><a href="register.html">Not registered?</a></td>
            </tr>
            </tbody>
        </table>
    </form:form>
</div>

src/main/webapp/WEB-INF/jsp/nav.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:if test="${not empty sessionScope.user}">
    <ul>
        <li><a href="home.html">My favourites</a></li>
        <li><a href="gallery.html">Gallery</a></li>
    </ul>
</c:if>

src/main/webapp/WEB-INF/jsp/register.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<h1>New user</h1>

<form:form action="register.html" commandName="userCommand" method="POST">
    <div id="userForm">
        <table>
            <tbody>
            <tr>
                <th/>
                <td><form:errors path="*" cssClass="redBold"/></td>
            </tr>
            <tr>
                <th><form:label path="username" cssErrorClass="redBold">Username</form:label></th>
                <td><form:input path="username"/></td>
            </tr>
            <tr>
                <th><form:label path="password" cssErrorClass="redBold">Password</form:label></th>
                <td><form:password path="password"/></td>
            </tr>
            <tr>
                <th><form:label path="password2"
                                cssErrorClass="redBold">Retype password</form:label></th>
                <td><form:password path="password2"/></td>
            </tr>
            <tr>
                <th>Sex</th>
                <td>
                    <form:radiobutton path="sex" value="F" label="Female"/>&nbsp;&nbsp;&nbsp;
                    <form:radiobutton path="sex" value="M" label="Male"/>
                </td>
            </tr>
            <tr>
                <th><form:label path="dobDay"
                                cssErrorClass="redBold">Date of birth</form:label></th>
                <td>
                    <form:select path="dobDay" items="${dobDays}"/>
                    <form:select path="dobMonth" items="${dobMonths}"/>
                    <form:select path="dobYear" items="${dobYears}"/>
                </td>
            </tr>
            <tr>
                <th><form:label path="postcode" cssErrorClass="redBold">Postcode</form:label></th>
                <td><form:input path="postcode"/></td>
            </tr>
            <tr>
                <td/>
                <td><input type="submit" value="Register" class="button"/></td>
            </tr>
            <tr>
                <td/>
                <td><a href="login.html">Back to login</a></td>
            </tr>
            </tbody>
        </table>
    </div>
</form:form>